<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<NorseDesignRef Include="Persistence.EntityFramework.Design">
			<Repo>Urdarbrunnr</Repo>
		</NorseDesignRef>
		<NorseRef Include="Infrastructure.Backend">
			<Repo>Midgard</Repo>
		</NorseRef>
		<NorseRef Include="Infrastructure.Web.Server">
			<Repo>Midgard</Repo>
		</NorseRef>
		<PackageReference Include="Microsoft.AspNetCore.TestHost" Version="11.*-*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.*-*" />
		<PackageReference Include="OpenTelemetry.Exporter.InMemory" Version="*" />
		<PackageReference Include="Testcontainers.PostgreSql" Version="*" />
		<ProjectReference Include="../../src/Identity.Migrations/Identity.Migrations.csproj" />
		<ProjectReference Include="../../src/Identity.Migrations.PostgreSQL/Identity.Migrations.PostgreSQL.csproj" />
		<ProjectReference Include="../../src/Identity.Web.Server/Identity.Web.Server.csproj" />
	</ItemGroup>
</Project>
