// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.Identity.Web.Server;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norse.Identity.Migrations.PostgreSQL.Migrations;

[DbContext(typeof(NorseIdentityDbContext))]
[Migration("20260723075913_InitialCreate")]
partial class _20260723075913_InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictApplication", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ApplicationType")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("application_type");

                b.Property<string>("ClientId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("client_id");

                b.Property<string>("ClientSecret")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("client_secret");

                b.Property<string>("ClientType")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("client_type");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("concurrency_token");

                b.Property<string>("ConsentType")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("consent_type");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_name");

                b.Property<string>("DisplayNames")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("display_names");

                b.Property<string>("JsonWebKeySet")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("json_web_key_set");

                b.Property<string>("Permissions")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("permissions");

                b.Property<string>("PostLogoutRedirectUris")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("post_logout_redirect_uris");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("properties");

                b.Property<string>("RedirectUris")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("redirect_uris");

                b.Property<string>("Requirements")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("requirements");

                b.Property<string>("Settings")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("settings");

                b.HasKey("Id")
                    .HasName("pk_applications");

                b.HasIndex("ClientId")
                    .IsUnique()
                    .HasDatabaseName("ix_applications_client_id");

                b.ToTable("applications");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("ApplicationId")
                    .HasColumnType("uuid")
                    .HasColumnName("application_id");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("concurrency_token");

                b.Property<DateTime?>("CreationDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("creation_date");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("properties");

                b.Property<string>("Scopes")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("scopes");

                b.Property<string>("Status")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("status");

                b.Property<string>("Subject")
                    .HasMaxLength(400)
                    .HasColumnType("character varying(400)")
                    .HasColumnName("subject");

                b.Property<string>("Type")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_authorizations");

                b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                    .HasDatabaseName("ix_authorizations_application_id_status_subject_type");

                b.ToTable("authorizations");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictScope", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("concurrency_token");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("description");

                b.Property<string>("Descriptions")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("descriptions");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_name");

                b.Property<string>("DisplayNames")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("display_names");

                b.Property<string>("Name")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("properties");

                b.Property<string>("Resources")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("resources");

                b.HasKey("Id")
                    .HasName("pk_scopes");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_scopes_name");

                b.ToTable("scopes");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("ApplicationId")
                    .HasColumnType("uuid")
                    .HasColumnName("application_id");

                b.Property<Guid?>("AuthorizationId")
                    .HasColumnType("uuid")
                    .HasColumnName("authorization_id");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("concurrency_token");

                b.Property<DateTime?>("CreationDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("creation_date");

                b.Property<DateTime?>("ExpirationDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expiration_date");

                b.Property<string>("Payload")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("payload");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("properties");

                b.Property<DateTime?>("RedemptionDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("redemption_date");

                b.Property<string>("ReferenceId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("reference_id");

                b.Property<string>("Status")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("status");

                b.Property<string>("Subject")
                    .HasMaxLength(400)
                    .HasColumnType("character varying(400)")
                    .HasColumnName("subject");

                b.Property<string>("Type")
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_tokens");

                b.HasIndex("AuthorizationId")
                    .HasDatabaseName("ix_tokens_authorization_id");

                b.HasIndex("ReferenceId")
                    .IsUnique()
                    .HasDatabaseName("ix_tokens_reference_id");

                b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                    .HasDatabaseName("ix_tokens_application_id_status_subject_type");

                b.ToTable("tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("uuid")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_name");

                b.HasKey("Id")
                    .HasName("pk_roles");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("role_name_index");

                b.ToTable("roles");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRoleClaim", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(id);

                b.Property<string>("ClaimType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .IsRequired()
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("pk_role_claims");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_role_claims_role_id");

                b.ToTable("role_claims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer")
                    .HasColumnName("access_failed_count");

                b.Property<Guid>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("uuid")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("email");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("email_confirmed");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("lockout_enabled");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("lockout_end");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_email");

                b.Property<string>("NormalizedUserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_user_name");

                b.Property<byte[]>("PasswordHash")
                    .HasMaxLength(128)
                    .HasColumnType("bytea")
                    .HasColumnName("password_hash");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("phone_number");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("phone_number_confirmed");

                b.Property<string>("SecurityStamp")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("security_stamp");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("two_factor_enabled");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("user_name");

                b.HasKey("Id")
                    .HasName("pk_users");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("email_index");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("user_name_index");

                b.ToTable("users");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserClaim", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(id);

                b.Property<string>("ClaimType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .IsRequired()
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_user_claims");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_claims_user_id");

                b.ToTable("user_claims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserLogin", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("login_provider");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_key");

                b.Property<string>("ProviderDisplayName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_display_name");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("LoginProvider", "ProviderKey")
                    .HasName("pk_user_logins");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_logins_user_id");

                b.ToTable("user_logins");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserPasskey", b =>
            {
                b.Property<byte[]>("CredentialId")
                    .HasMaxLength(1024)
                    .HasColumnType("bytea")
                    .HasColumnName("credential_id");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "Norse.Identity.Web.Server.NorseUserPasskey.Data#IdentityPasskeyData", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<byte[]>("Aaguid");

                        b1.Property<byte[]>("AttestationObject")
                            .IsRequired();

                        b1.Property<byte[]>("ClientDataJson")
                            .IsRequired();

                        b1.Property<DateTimeOffset>("CreatedAt");

                        b1.Property<bool>("IsBackedUp");

                        b1.Property<bool>("IsBackupEligible");

                        b1.Property<bool>("IsUserVerified");

                        b1.Property<string>("Name");

                        b1.Property<byte[]>("PublicKey")
                            .IsRequired();

                        b1.Property<long>("SignCount");

                        b1.PrimitiveCollection<string>("Transports");

                        b1
                            .ToJson("data")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("CredentialId")
                    .HasName("pk_user_passkeys");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_passkeys_user_id");

                b.ToTable("user_passkeys");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("role_id");

                b.HasKey("UserId", "RoleId")
                    .HasName("pk_user_roles");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_user_roles_role_id");

                b.ToTable("user_roles");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserToken", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("login_provider");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("name");

                b.Property<string>("Value")
                    .HasMaxLength(-1)
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("UserId", "LoginProvider", "Name")
                    .HasName("pk_user_tokens");

                b.ToTable("user_tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictApplication", "Application")
                    .WithMany("Authorizations")
                    .HasForeignKey("ApplicationId")
                    .HasConstraintName("fk_authorizations_applications_application_id");

                b.Navigation("Application");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictToken", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictApplication", "Application")
                    .WithMany("Tokens")
                    .HasForeignKey("ApplicationId")
                    .HasConstraintName("fk_tokens_applications_application_id");

                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", "Authorization")
                    .WithMany("Tokens")
                    .HasForeignKey("AuthorizationId")
                    .HasConstraintName("fk_tokens_authorizations_authorization_id");

                b.Navigation("Application");

                b.Navigation("Authorization");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRoleClaim", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseRole", "Role")
                    .WithMany("Claims")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_role_claims_roles_role_id");

                b.Navigation("Role");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserClaim", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Claims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_claims_users_user_id");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserLogin", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Logins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_logins_users_user_id");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserPasskey", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Passkeys")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_passkeys_users_user_id");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserRole", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseRole", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_roles_roles_role_id");

                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_roles_users_user_id");

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserToken", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Tokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_tokens_users_user_id");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictApplication", b =>
            {
                b.Navigation("Authorizations");

                b.Navigation("Tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.Navigation("Tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRole", b =>
            {
                b.Navigation("Claims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUser", b =>
            {
                b.Navigation("Claims");

                b.Navigation("Logins");

                b.Navigation("Passkeys");

                b.Navigation("Tokens");
            });
#pragma warning restore 612, 618
    }
}
