<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<NorseDesignRef Include="Persistence.EntityFramework.Design">
			<Repo>Urdarbrunnr</Repo>
		</NorseDesignRef>
		<PackageReference Include="Testcontainers.PostgreSql" Version="*" />
		<ProjectReference Include="../../src/Identity.Migrations/Identity.Migrations.csproj" />
		<ProjectReference Include="../../src/Identity.Migrations.PostgreSQL/Identity.Migrations.PostgreSQL.csproj" />
	</ItemGroup>
</Project>
