-- ============================================================
-- AUTO-GENERATED BY EF CORE MIGRATIONS — DO NOT EDIT BY HAND
-- Changes made here will be overwritten on the next migration.
-- Run: dotnet ef migrations add <Name> to update this file.
-- ============================================================
CREATE TABLE applications (
    id uuid NOT NULL,
    application_type character varying(50),
    client_id character varying(100),
    client_secret text,
    client_type character varying(50),
    concurrency_token character varying(50),
    consent_type character varying(50),
    display_name character varying(200),
    display_names text,
    json_web_key_set text,
    permissions text,
    post_logout_redirect_uris text,
    properties text,
    redirect_uris text,
    requirements text,
    settings text,
    CONSTRAINT pk_applications PRIMARY KEY (id)
);


CREATE TABLE roles (
    id uuid NOT NULL,
    name character varying(256) NOT NULL,
    normalized_name character varying(256) NOT NULL,
    concurrency_stamp uuid NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);


CREATE TABLE scopes (
    id uuid NOT NULL,
    concurrency_token character varying(50),
    description character varying(1000),
    descriptions text,
    display_name character varying(200),
    display_names text,
    name character varying(200),
    properties text,
    resources text,
    CONSTRAINT pk_scopes PRIMARY KEY (id)
);


CREATE TABLE users (
    id uuid NOT NULL,
    security_stamp character varying(32) NOT NULL,
    user_name character varying(256) NOT NULL,
    normalized_user_name character varying(256) NOT NULL,
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash bytea,
    concurrency_stamp uuid NOT NULL,
    phone_number character varying(20),
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE authorizations (
    id uuid NOT NULL,
    application_id uuid,
    concurrency_token character varying(50),
    creation_date timestamp with time zone,
    properties text,
    scopes text,
    status character varying(50),
    subject character varying(400),
    type character varying(50),
    CONSTRAINT pk_authorizations PRIMARY KEY (id),
    CONSTRAINT fk_authorizations_applications_application_id FOREIGN KEY (application_id) REFERENCES applications (id)
);


CREATE TABLE role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type character varying(256) NOT NULL,
    claim_value text NOT NULL,
    CONSTRAINT pk_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_role_claims_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);


CREATE TABLE user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type character varying(256) NOT NULL,
    claim_value text NOT NULL,
    CONSTRAINT pk_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE user_logins (
    login_provider character varying(128) NOT NULL,
    provider_key character varying(256) NOT NULL,
    provider_display_name character varying(256),
    user_id uuid NOT NULL,
    CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE user_passkeys (
    credential_id bytea NOT NULL,
    user_id uuid NOT NULL,
    "Data" jsonb NOT NULL,
    CONSTRAINT pk_user_passkeys PRIMARY KEY (credential_id),
    CONSTRAINT fk_user_passkeys_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE user_tokens (
    user_id uuid NOT NULL,
    login_provider character varying(128) NOT NULL,
    name character varying(128) NOT NULL,
    value text,
    CONSTRAINT pk_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_user_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE tokens (
    id uuid NOT NULL,
    application_id uuid,
    authorization_id uuid,
    concurrency_token character varying(50),
    creation_date timestamp with time zone,
    expiration_date timestamp with time zone,
    payload text,
    properties text,
    redemption_date timestamp with time zone,
    reference_id character varying(100),
    status character varying(50),
    subject character varying(400),
    type character varying(150),
    CONSTRAINT pk_tokens PRIMARY KEY (id),
    CONSTRAINT fk_tokens_applications_application_id FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT fk_tokens_authorizations_authorization_id FOREIGN KEY (authorization_id) REFERENCES authorizations (id)
);


CREATE UNIQUE INDEX ix_applications_client_id ON applications (client_id);


CREATE INDEX ix_authorizations_application_id_status_subject_type ON authorizations (application_id, status, subject, type);


CREATE INDEX ix_role_claims_role_id ON role_claims (role_id);


CREATE UNIQUE INDEX role_name_index ON roles (normalized_name);


CREATE UNIQUE INDEX ix_scopes_name ON scopes (name);


CREATE INDEX ix_tokens_application_id_status_subject_type ON tokens (application_id, status, subject, type);


CREATE INDEX ix_tokens_authorization_id ON tokens (authorization_id);


CREATE UNIQUE INDEX ix_tokens_reference_id ON tokens (reference_id);


CREATE INDEX ix_user_claims_user_id ON user_claims (user_id);


CREATE INDEX ix_user_logins_user_id ON user_logins (user_id);


CREATE INDEX ix_user_passkeys_user_id ON user_passkeys (user_id);


CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);


CREATE INDEX email_index ON users (normalized_email);


CREATE UNIQUE INDEX user_name_index ON users (normalized_user_name);


