// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.Identity.Web.Server;

#nullable disable

namespace Norse.Identity.Migrations.SqlServer.Migrations;

[DbContext(typeof(NorseIdentityDbContext))]
partial class NorseIdentityDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260723080838_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictApplication", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ApplicationType")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ClientId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ClientSecret")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClientType")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ConsentType")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("DisplayNames")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("JsonWebKeySet")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Permissions")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PostLogoutRedirectUris")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RedirectUris")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Requirements")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Settings")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ClientId")
                    .IsUnique()
                    .HasFilter("[ClientId] IS NOT NULL");

                b.ToTable("Applications");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ApplicationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Scopes")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Subject")
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Type")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                b.ToTable("Authorizations");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictScope", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Descriptions")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("DisplayNames")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Resources")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasFilter("[Name] IS NOT NULL");

                b.ToTable("Scopes");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ApplicationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("AuthorizationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ExpirationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Payload")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Properties")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("RedemptionDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ReferenceId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Status")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Subject")
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Type")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("Id");

                b.HasIndex("AuthorizationId");

                b.HasIndex("ReferenceId")
                    .IsUnique()
                    .HasFilter("[ReferenceId] IS NOT NULL");

                b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                b.ToTable("Tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("Roles");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRoleClaim", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("ClaimType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("ClaimValue")
                    .IsRequired()
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("RoleClaims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<Guid>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<byte[]>("PasswordHash")
                    .HasMaxLength(128)
                    .HasColumnType("varbinary(128)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("nchar(32)")
                    .IsFixedLength();

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("Users");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserClaim", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("ClaimType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("ClaimValue")
                    .IsRequired()
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("UserClaims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserLogin", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("ProviderDisplayName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("UserLogins");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserPasskey", b =>
            {
                b.Property<byte[]>("CredentialId")
                    .HasMaxLength(1024)
                    .HasColumnType("varbinary(1024)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "Norse.Identity.Web.Server.NorseUserPasskey.Data#IdentityPasskeyData", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<byte[]>("Aaguid");

                        b1.Property<byte[]>("AttestationObject")
                            .IsRequired();

                        b1.Property<byte[]>("ClientDataJson")
                            .IsRequired();

                        b1.Property<DateTimeOffset>("CreatedAt");

                        b1.Property<bool>("IsBackedUp");

                        b1.Property<bool>("IsBackupEligible");

                        b1.Property<bool>("IsUserVerified");

                        b1.Property<string>("Name");

                        b1.Property<byte[]>("PublicKey")
                            .IsRequired();

                        b1.Property<long>("SignCount");

                        b1.PrimitiveCollection<string>("Transports");

                        b1
                            .ToJson("Data")
                            .HasColumnType("json");
                    });

                b.HasKey("CredentialId");

                b.HasIndex("UserId");

                b.ToTable("UserPasskeys");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("UserRoles");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserToken", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Value")
                    .HasMaxLength(-1)
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("UserTokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictApplication", "Application")
                    .WithMany("Authorizations")
                    .HasForeignKey("ApplicationId");

                b.Navigation("Application");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictToken", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictApplication", "Application")
                    .WithMany("Tokens")
                    .HasForeignKey("ApplicationId");

                b.HasOne("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", "Authorization")
                    .WithMany("Tokens")
                    .HasForeignKey("AuthorizationId");

                b.Navigation("Application");

                b.Navigation("Authorization");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRoleClaim", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseRole", "Role")
                    .WithMany("Claims")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserClaim", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Claims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserLogin", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Logins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserPasskey", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Passkeys")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserRole", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseRole", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUserToken", b =>
            {
                b.HasOne("Norse.Identity.Web.Server.NorseUser", "User")
                    .WithMany("Tokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictApplication", b =>
            {
                b.Navigation("Authorizations");

                b.Navigation("Tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseOpenIddictAuthorization", b =>
            {
                b.Navigation("Tokens");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseRole", b =>
            {
                b.Navigation("Claims");
            });

        modelBuilder.Entity("Norse.Identity.Web.Server.NorseUser", b =>
            {
                b.Navigation("Claims");

                b.Navigation("Logins");

                b.Navigation("Passkeys");

                b.Navigation("Tokens");
            });
#pragma warning restore 612, 618
    }
}
